(test
 (name test_awskit_s3_sim)
 (package awskit-s3-sim)
 (libraries
  awskit
  awskit-s3
  awskit-s3-sim
  awskit_s3_test
  alcotest
  ptime
  qcheck-core
  qcheck-alcotest))

(rule
 (alias simulator-contract)
 (package awskit-s3-sim)
 (deps test_awskit_s3_sim.exe)
 (action
  (run ./test_awskit_s3_sim.exe)))

(rule
 (alias simulator-stateful-pbt)
 (package awskit-s3-sim)
 (deps test_awskit_s3_sim.exe)
 (action
  (run ./test_awskit_s3_sim.exe test "pbt:awskit-s3-sim:simulator-stateful")))
