(test
 (name test_awskit_s3)
 (package awskit-s3)
 (libraries
  awskit
  awskit_test
  awskit-s3
  awskit_s3_test
  alcotest
  qcheck-core
  qcheck-alcotest
  ptime))

(rule
 (alias protocol-pbt)
 (deps test_awskit_s3.exe)
 (action
  (progn
   (run ./test_awskit_s3.exe test "pbt:domain:bucket")
   (run ./test_awskit_s3.exe test "pbt:domain:key")
   (run ./test_awskit_s3.exe test "pbt:domain:account-metadata-tags")
   (run ./test_awskit_s3.exe test "pbt:paginator")
   (run ./test_awskit_s3.exe test "pbt:transfer-plan"))))
