(test
 (name test_awskit_s3)
 (package awskit-s3)
 (libraries
  awskit
  awskit_test
  awskit-s3
  awskit_s3_test
  alcotest
  qcheck-core
  qcheck-alcotest
  ptime))

(rule
 (alias protocol-pbt)
 (package awskit-s3)
 (deps test_awskit_s3.exe)
 (action
  (progn
   (run ./test_awskit_s3.exe test "pbt:awskit-s3:domain:bucket")
   (run ./test_awskit_s3.exe test "pbt:awskit-s3:domain:key")
   (run
    ./test_awskit_s3.exe
    test
    "pbt:awskit-s3:domain:account-metadata-tags")
   (run ./test_awskit_s3.exe test "pbt:awskit-s3:paginator")
   (run ./test_awskit_s3.exe test "pbt:awskit-s3:bucket-xml")
   (run ./test_awskit_s3.exe test "pbt:awskit-s3:transfer-plan"))))
