(alias
 (name check-quick)
 (deps
  dune-project
  (alias awskit-core-contracts)
  (alias awskit-runtime-contracts)
  (alias runtime-http)
  (alias s3-sim)
  (alias s3-transfer)
  (alias s3-domain)
  (alias s3-protocol)
  (alias s3-protocol-fixtures)
  (alias s3-protocol-replay)))

(alias
 (name check-integration)
 (deps
  dune-project
  (alias s3-minio)))

(alias
 (name check-full)
 (deps
  dune-project
  (alias check-quick)
  (alias_rec examples)
  (alias_rec doc)
  (alias check-integration)))

(alias
 (name check-stress)
 (deps
  dune-project
  (alias check-quick)
  (alias_rec discovery)))

(alias
 (name runtime-http)
 (deps
  (alias test/awskit/eio/runtime-http)
  (alias test/awskit/lwt/runtime-http)))

(alias
 (name awskit-core-contracts)
 (deps
  (alias test/awskit/awskit-core-contracts)))

(alias
 (name awskit-runtime-contracts)
 (deps
  (alias test/awskit/runtime/awskit-runtime-contracts)))

(alias
 (name s3-sim)
 (deps
  (alias test/awskit-s3/sim/s3-state)))

(alias
 (name s3-transfer)
 (deps
  (alias test/awskit-s3/sim/s3-transfer)))

(alias
 (name s3-domain)
 (deps
  (alias test/awskit-s3/protocol/domain)))

(alias
 (name s3-protocol)
 (deps
  (alias test/awskit-s3/protocol/wire)))

(alias
 (name s3-protocol-fixtures)
 (deps
  (alias test/awskit-s3/protocol/fixtures)))

(alias
 (name s3-protocol-replay)
 (deps
  (alias test/awskit-s3/protocol/replay)))

(alias
 (name s3-minio)
 (deps
  (alias test/awskit-s3/lwt/unix/s3-minio)))
