(test
 (name test_awskit_s3_lwt_unix)
 (package awskit-s3-lwt-unix)
 (modules
  test_awskit_s3_lwt_unix
  test_integration
  test_transfer
  transfer_under_test)
 (libraries
  awskit
  awskit-lwt-unix
  awskit-unix
  awskit-s3
  awskit-s3-lwt-unix
  lwt
  lwt.unix
  fmt
  alcotest))

(rule
 (target transfer_under_test.ml)
 (deps ../../../../packages/awskit-s3/lwt/unix/transfer.ml)
 (action
  (copy %{deps} %{target})))

(executable
 (name test_minio_contract)
 (modules test_minio_contract)
 (libraries
  awskit
  awskit-lwt-unix
  awskit-s3
  awskit-s3-lwt-unix
  awskit_s3_test
  lwt
  lwt.unix
  ptime.clock.os
  alcotest))

(rule
 (alias minio-contract)
 (package awskit-s3-lwt-unix)
 (action
  (run ./test_minio_contract.exe)))
