module Core : module type of Core
module Metadata : module type of Metadata
module Storage_class : module type of Storage_class
module Tag : module type of Tag
module Range : module type of Range
module Endpoint_resolver : module type of Endpoint_resolver
module Object : module type of Object
module Bucket : module type of Bucket
module Multipart : module type of Multipart
module Transfer : module type of Transfer
module Policy : module type of Policy
module Presigned : module type of Presigned
module Make : module type of Make
module Headers : module type of Headers
