(test
 (name test_awskit_lwt)
 (package awskit-lwt)
 (libraries
  awskit
  awskit-lwt
  awskit_runtime_http_contract
  cohttp-lwt-unix
  ptime
  alcotest))

(rule
 (alias runtime-http-contract)
 (package awskit-lwt)
 (deps test_awskit_lwt.exe)
 (action
  (run ./test_awskit_lwt.exe test "contract:awskit-lwt:runtime-http")))

(rule
 (alias runtime-conformance)
 (package awskit-lwt)
 (deps
  (alias runtime-http-contract)
  test_awskit_lwt.exe)
 (action
  (run ./test_awskit_lwt.exe test "integration:awskit-lwt:connection")))
