((application_sdk
  (Awskit
   Awskit.Credentials
   Awskit.Region
   Awskit.Endpoint
   Awskit.Error
   Awskit.Timeout
   Awskit_s3
   Awskit_s3.Account_id
   Awskit_s3.Bucket
   Awskit_s3.Bucket_name
   Awskit_s3.Content_type
   Awskit_s3.Header_value
   Awskit_s3.Metadata
   Awskit_s3.Multipart
   Awskit_s3.Object
   Awskit_s3.Object_key
   Awskit_s3.Presigned
   Awskit_s3.Range
   Awskit_s3.Storage_class
   Awskit_s3.Tag
   Awskit_s3.Transfer))
 (advanced_application_api
  (Awskit.Body
   Awskit.Retry
   Awskit.Request
   Awskit.Response
   Awskit.Signing
   Awskit_s3.Endpoint_config
   Awskit_s3.Endpoint_resolver
   Awskit_s3.Policy
   Awskit_s3_lwt
   Awskit_s3_lwt_unix
   Awskit_s3_eio))
 (runtime_api
  (Awskit.Runtime
   Awskit_unix
   Awskit_lwt
   Awskit_lwt_unix
   Awskit_eio
   Awskit_s3.RUNTIME
   Awskit_s3.BODY
   Awskit_s3.READER
   Awskit_s3.OBJECT
   Awskit_s3.BUCKET
   Awskit_s3.MULTIPART
   Awskit_s3.PRESIGNED
   Awskit_s3.S
   Awskit_s3.Make))
 (simulator_api
  (Awskit_s3_sim))
 (private_implementation_debt
  (Awskit.Error.Internal
   Awskit_s3.Awskit_s3_intf)))
