(test
 (name test_core_contracts)
 (package awskit)
 (libraries awskit base ptime alcotest qcheck-core qcheck-alcotest))

(rule
 (alias awskit-core-contracts)
 (package awskit)
 (deps
  test_core_contracts.exe
  (env_var AWSKIT_QCHECK_COUNT)
  (env_var QCHECK_SEED))
 (action
  (run ./test_core_contracts.exe)))
